---
- name: Verify
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Run version check
      ansible.builtin.command:
        cmd: gitlab-runner --version
      changed_when: false
